### ISSUE TITLE
请问如何同意好友申请？

### ISSUE THREAD

**Issue by go3k** [hexsum/pfqq#7]
RT 可以实现吗？
PS. 这个项目真好玩！ :+1:

**Comment by sjdy521** [comment]
在PC端QQ上设置加好友不需要认证，这样对方加你好友时就直接通过了，但因为你并没有加对方为好友，所以对方会出现在你的陌生人分组里，实际上已经可以发送好友消息了。
另外，这个项目之前代码写的比较乱，项目正在重构，请多关注

**Comment by go3k** [comment]
好的，多谢

**Comment by go3k** [comment]
@sjdy521 开了SmartReply...但是很快就被腾讯认定为“发不良信息 --- 账号疑似被盗，正处于保护模式中。”
这种问题有什么经验吗？

**Comment by sjdy521** [comment]
@go3k 这个问题实际上研究起来比较深奥 腾讯肯定有自己的一套机器学习算法，能够识别一些疑似"不良信息"的内容，识别的规则可能是内容中包含某些关键词，比如"转账"，或者经常发一些链接，或者是经常发相似内容，或者回复速度太快，等等，要搞清楚这个只能够尽量摸索，积累经验，避免发送可能产生问题的内容，先前我自己的帐号也经常因为出现这样的问题

另外，要尽量提高自己的账号安全性，比如帐号进行了手机绑定、密码不是弱口令、手机安装腾讯的”QQ安全中心" APP，发现帐号异常第一时间确认，进入保护模式及时用APP解锁

**Comment by go3k** [comment]
ok

**Comment by ljkgpxs** [comment]
额。。运行demo。。会自动同意群邀请。。

**Comment by sjdy521** [comment]
@ljkgpxs
那是因为你的QQ在PC端的设置默认就允许通过群邀请直接加入群中
